### ISSUE TITLE
Atom 1.16 seemed to break the plugin

### ISSUE THREAD

**Issue by az-z** [AnickaBurova/cpp-refactor#3]
Hello,
 i just updated to latest Atom (1.16.0 on Fedora 25 ) and i can't invoke the plugin functionality ( by pressing alt-ctrl -r ) at all.  Do you mind to check that it is still working, please?

**Comment by AnickaBurova** [comment]
Hi,
I am running version 1.18 and it is working. Cannot reproduce this problem. I have added some additional shortcuts, but that is all I can do for now.
