### ISSUE TITLE
Q: Does it still function ?

### ISSUE THREAD

**Issue by HeinrichGit** [AnickaBurova/cpp-refactor#4]
1) Is it possible to provide some more detailed readme of how it is suppose to work?

2) It just crashed after trying cmd+alt+r c. Does this package still function? Is it still maintained?

**Comment by AnickaBurova** [comment]
Hi,
I stopped using atom, but still fixed some last issue with regex. On latest version 1.18 running on linux I can't reproduce your problem. Alt+ctrl+r c does exactly what is suppose to do.
I no longer run mac, so there is no way for me to test there.
Thanks
